### ISSUE TITLE
Worker v3.8.2 rollout tracking

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/terraform-config#483]
This issue is meant to track the rollout of `travis-worker` v3.8.2 as introduced in #481 

- [x] aws-production-2
- [x] gce-production-1
- [x] gce-production-2
- [x] gce-production-3
- [x] gce-production-4
- [x] ~gce-production-5~ (currently disabled)
- [x] ~macstadium-pod-1~ (deferring)
- [x] ~macstadium-pod-2~ (deferring)
- [x] packet-production-1

**Comment by bogdanap** [comment]
I have applied the changes to aws-production-2, in order to test the config change in https://github.com/travis-ci/terraform-config/pull/487. 
Will keep an eye on things for the next few hours.
